[package]
authors = ["The RustWasm Developers"]
categories = ["wasm"]
description = "My super awesome Rust, WebAssembly, and Webpack project!"
license = "Apache-2.0/MIT"
name = "rust-webpack"
readme = "./README.md"
repository = "https://github.com/rustwasm/rust-webpack-template"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
cfg-if = "^0.1.5"
wasm-bindgen = "^0.2.25"
js-sys = "^0.3.2"
rand = { git = "https://github.com/rust-random/rand.git", features = ["wasm-bindgen"] }
fnv = "^1.0.3"
nalgebra = "^0.16.5"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "^0.1.5", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
wee_alloc = { version = "^0.4.2", optional = true }

[dependencies.web-sys]
version = "^0.3.2"
features = [
  'console',
  'Document',
  'HtmlCanvasElement',
  'HtmlElement',
  'Element',
  'Window',
  'HtmlCanvasElement',
  'WebGlBuffer',
  'WebGl2RenderingContext',
  'WebGlProgram',
  'WebGlShader',
  'WebGlVertexArrayObject',
  'WebGlUniformLocation'
]

[dependencies.specs]
git = "https://github.com/bgourlie/specs.git"
default-features = false

[features]
default-features = ["console_error_panic_hook", "wee_alloc"]
